name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...
      
    - name: Test
      run: go test -v ./...
      
  create-tag:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    
    - name: Creating Tag
      uses: jsok/svu-version-bump-action@v2
      with:
        bump: "next"
